name: smart-serve-backend

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRADLE_VERSION: "${GRADLE_VERSION:-8.10.2}"
    volumes:
      - ../:/workspace:cached,Z
      - gradle-cache:/home/vscode/.gradle/
    command: sleep infinity
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JAVA_HOME: /usr/local/sdkman/candidates/java/current
      GRADLE_VERSION: ${GRADLE_VERSION}
    networks:
      - spring-network

networks:
  spring-network:
    name: auth-service_spring-network
    external: true

volumes:
  gradle-cache:
